image:
  name: dtzar/helm-kubectl
  tag: latest
  imagePullSecrets: nvcr.io
  pullPolicy: Always


dataConfig:
  ContainerImage: nvcr.io/ea-bignlp/ga-participants/nemofw-training:23.08.02

  ShmSize: 512Gi

  # Insert the pvc name for the NFS if using NFS for model storage #
  NFSPersistentVolumeClaimName: <Insert NFS pvc name>
  # Insert the address for the NFS server if using NFS for model storage #
  NFSServer: <Insert NFS server address>
  # Insert the path to save data on the NFS server #
  NFSPath: /data

  IBResourceName: "nvidia.com/hostdev"
  IBResourceCount: 0
